[2024-01-12T17:47:45.247+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_fdic_ncua.fdic.extract_fdic_financials manual__2024-01-12T17:47:44.059907+00:00 [queued]>
[2024-01-12T17:47:45.255+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_fdic_ncua.fdic.extract_fdic_financials manual__2024-01-12T17:47:44.059907+00:00 [queued]>
[2024-01-12T17:47:45.256+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-12T17:47:45.263+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): fdic.extract_fdic_financials> on 2024-01-12 17:47:44.059907+00:00
[2024-01-12T17:47:45.267+0000] {standard_task_runner.py:60} INFO - Started process 6735 to run task
[2024-01-12T17:47:45.272+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_fdic_ncua', 'fdic.extract_fdic_financials', 'manual__2024-01-12T17:47:44.059907+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/fdic-ncua-ingest.py', '--cfg-path', '/tmp/tmpuaxxkdo7']
[2024-01-12T17:47:45.273+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask fdic.extract_fdic_financials
[2024-01-12T17:47:45.342+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_fdic_ncua.fdic.extract_fdic_financials manual__2024-01-12T17:47:44.059907+00:00 [running]> on host c111cf247bc6
[2024-01-12T17:47:45.393+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_fdic_ncua' AIRFLOW_CTX_TASK_ID='fdic.extract_fdic_financials' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T17:47:44.059907+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T17:47:44.059907+00:00'
[2024-01-12T17:47:45.394+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fdic-ncua-ingest.py", line 51, in extract_fdic_financials
    insert_to_pg(hook=pg_hook, schema='raw', table='fdic_financials', data=get_fdic_data("/financials", today_dt=today, last_quarter_dt=last_quarter))
TypeError: get_fdic_data() got an unexpected keyword argument 'today_dt'
[2024-01-12T17:47:45.400+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_fdic_ncua, task_id=fdic.extract_fdic_financials, execution_date=20240112T174744, start_date=20240112T174745, end_date=20240112T174745
[2024-01-12T17:47:45.406+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task fdic.extract_fdic_financials (get_fdic_data() got an unexpected keyword argument 'today_dt'; 6735)
[2024-01-12T17:47:45.446+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T17:47:45.456+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
