[2024-01-12T14:58:54.395+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T14:58:53.054056+00:00 [queued]>
[2024-01-12T14:58:54.401+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T14:58:53.054056+00:00 [queued]>
[2024-01-12T14:58:54.401+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-12T14:58:54.408+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): ncua_extract.extract_ncua_call_report_data> on 2024-01-12 14:58:53.054056+00:00
[2024-01-12T14:58:54.412+0000] {standard_task_runner.py:60} INFO - Started process 4027 to run task
[2024-01-12T14:58:54.416+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_fdic_ncua', 'ncua_extract.extract_ncua_call_report_data', 'manual__2024-01-12T14:58:53.054056+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/fdic-ncua-ingest.py', '--cfg-path', '/tmp/tmpj72_sh49']
[2024-01-12T14:58:54.417+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask ncua_extract.extract_ncua_call_report_data
[2024-01-12T14:58:54.443+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T14:58:53.054056+00:00 [running]> on host c111cf247bc6
[2024-01-12T14:58:54.479+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_fdic_ncua' AIRFLOW_CTX_TASK_ID='ncua_extract.extract_ncua_call_report_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T14:58:53.054056+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T14:58:53.054056+00:00'
[2024-01-12T14:58:55.251+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fdic-ncua-ingest.py", line 64, in extract_ncua_call_report_data
    ncua_call_report_to_s3(s3_hook, lq_year, lq_month)
  File "/opt/airflow/dags/utils/core/ncua/ncua.py", line 16, in ncua_call_report_to_s3
    hook.load_string(string_data=c, key=f'ncua-call-report-data/{year}-{quarter}.zip', bucket_name='alpharank-de-eval')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1124, in load_string
    bytes_data = string_data.encode(encoding)
AttributeError: 'bytes' object has no attribute 'encode'
[2024-01-12T14:58:55.267+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_fdic_ncua, task_id=ncua_extract.extract_ncua_call_report_data, execution_date=20240112T145853, start_date=20240112T145854, end_date=20240112T145855
[2024-01-12T14:58:55.278+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task ncua_extract.extract_ncua_call_report_data ('bytes' object has no attribute 'encode'; 4027)
[2024-01-12T14:58:55.296+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T14:58:55.310+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
