[2024-01-12T14:57:22.757+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T14:57:22.034598+00:00 [queued]>
[2024-01-12T14:57:22.762+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T14:57:22.034598+00:00 [queued]>
[2024-01-12T14:57:22.763+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-12T14:57:22.769+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): ncua_extract.extract_ncua_call_report_data> on 2024-01-12 14:57:22.034598+00:00
[2024-01-12T14:57:22.772+0000] {standard_task_runner.py:60} INFO - Started process 4001 to run task
[2024-01-12T14:57:22.777+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_fdic_ncua', 'ncua_extract.extract_ncua_call_report_data', 'manual__2024-01-12T14:57:22.034598+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/fdic-ncua-ingest.py', '--cfg-path', '/tmp/tmp8s_r56g3']
[2024-01-12T14:57:22.778+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask ncua_extract.extract_ncua_call_report_data
[2024-01-12T14:57:22.817+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T14:57:22.034598+00:00 [running]> on host c111cf247bc6
[2024-01-12T14:57:22.859+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_fdic_ncua' AIRFLOW_CTX_TASK_ID='ncua_extract.extract_ncua_call_report_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T14:57:22.034598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T14:57:22.034598+00:00'
[2024-01-12T14:57:23.553+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fdic-ncua-ingest.py", line 64, in extract_ncua_call_report_data
    ncua_call_report_to_s3(s3_hook, lq_year, lq_month)
  File "/opt/airflow/dags/utils/core/ncua/ncua.py", line 15, in ncua_call_report_to_s3
    hook.upload_fileobj(fileobj, 'alpharank-de-eval', f'ncua-call-report-data/{year}-{quarter}.zip')
AttributeError: 'S3Hook' object has no attribute 'upload_fileobj'
[2024-01-12T14:57:23.563+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_fdic_ncua, task_id=ncua_extract.extract_ncua_call_report_data, execution_date=20240112T145722, start_date=20240112T145722, end_date=20240112T145723
[2024-01-12T14:57:23.570+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 28 for task ncua_extract.extract_ncua_call_report_data ('S3Hook' object has no attribute 'upload_fileobj'; 4001)
[2024-01-12T14:57:23.581+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T14:57:23.596+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
