[2024-01-12T15:04:25.823+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T15:04:24.401628+00:00 [queued]>
[2024-01-12T15:04:25.828+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T15:04:24.401628+00:00 [queued]>
[2024-01-12T15:04:25.829+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-12T15:04:25.835+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): ncua_extract.extract_ncua_call_report_data> on 2024-01-12 15:04:24.401628+00:00
[2024-01-12T15:04:25.839+0000] {standard_task_runner.py:60} INFO - Started process 4137 to run task
[2024-01-12T15:04:25.842+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_fdic_ncua', 'ncua_extract.extract_ncua_call_report_data', 'manual__2024-01-12T15:04:24.401628+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/fdic-ncua-ingest.py', '--cfg-path', '/tmp/tmpih8f9213']
[2024-01-12T15:04:25.843+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask ncua_extract.extract_ncua_call_report_data
[2024-01-12T15:04:25.871+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_fdic_ncua.ncua_extract.extract_ncua_call_report_data manual__2024-01-12T15:04:24.401628+00:00 [running]> on host c111cf247bc6
[2024-01-12T15:04:25.909+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_fdic_ncua' AIRFLOW_CTX_TASK_ID='ncua_extract.extract_ncua_call_report_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T15:04:24.401628+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T15:04:24.401628+00:00'
[2024-01-12T15:04:30.235+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fdic-ncua-ingest.py", line 64, in extract_ncua_call_report_data
    ncua_call_report_to_s3(s3_hook, lq_year, lq_month)
  File "/opt/airflow/dags/utils/core/ncua/ncua.py", line 18, in ncua_call_report_to_s3
    hook.load_string(string_data=fileobj, key=f'ncua-call-report-data/{year}-{quarter}.zip', bucket_name='alpharank-de-eval')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1124, in load_string
    bytes_data = string_data.encode(encoding)
AttributeError: '_io.BytesIO' object has no attribute 'encode'
[2024-01-12T15:04:30.243+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_fdic_ncua, task_id=ncua_extract.extract_ncua_call_report_data, execution_date=20240112T150424, start_date=20240112T150425, end_date=20240112T150430
[2024-01-12T15:04:30.250+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task ncua_extract.extract_ncua_call_report_data ('_io.BytesIO' object has no attribute 'encode'; 4137)
[2024-01-12T15:04:30.257+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T15:04:30.274+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
