[2024-01-11T22:35:51.491+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_fdic_ncua.fdic.extract_fdic_financials manual__2024-01-11T22:35:49.696923+00:00 [queued]>
[2024-01-11T22:35:51.499+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_fdic_ncua.fdic.extract_fdic_financials manual__2024-01-11T22:35:49.696923+00:00 [queued]>
[2024-01-11T22:35:51.500+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-11T22:35:51.509+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): fdic.extract_fdic_financials> on 2024-01-11 22:35:49.696923+00:00
[2024-01-11T22:35:51.512+0000] {standard_task_runner.py:60} INFO - Started process 3265 to run task
[2024-01-11T22:35:51.517+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_fdic_ncua', 'fdic.extract_fdic_financials', 'manual__2024-01-11T22:35:49.696923+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/fdic-ncua-ingest.py', '--cfg-path', '/tmp/tmppuqu47_0']
[2024-01-11T22:35:51.518+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask fdic.extract_fdic_financials
[2024-01-11T22:35:51.579+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_fdic_ncua.fdic.extract_fdic_financials manual__2024-01-11T22:35:49.696923+00:00 [running]> on host c111cf247bc6
[2024-01-11T22:35:51.626+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_fdic_ncua' AIRFLOW_CTX_TASK_ID='fdic.extract_fdic_financials' AIRFLOW_CTX_EXECUTION_DATE='2024-01-11T22:35:49.696923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-11T22:35:49.696923+00:00'
[2024-01-11T22:35:51.629+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fdic-ncua-ingest.py", line 53, in extract_fdic_financials
    response = fdic_request("/financials", offset=offset, limit=limit)
  File "/opt/airflow/dags/utils/core/fdic/fdic.py", line 16, in fdic_request
    last_quarter = previous_quarter(today).strftime('%Y%m%d')
  File "/opt/airflow/dags/utils/core/helpers/helpers.py", line 4, in previous_quarter
    if ref.month < 4:
AttributeError: 'str' object has no attribute 'month'
[2024-01-11T22:35:51.643+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_fdic_ncua, task_id=fdic.extract_fdic_financials, execution_date=20240111T223549, start_date=20240111T223551, end_date=20240111T223551
[2024-01-11T22:35:51.660+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task fdic.extract_fdic_financials ('str' object has no attribute 'month'; 3265)
[2024-01-11T22:35:51.696+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-11T22:35:51.708+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
